version: '3.4'
networks:
  grpc_network:
services:
  user:
    image: user
    container_name: user
    environment:
      GRPC_SERVER: grpc-nginx
    networks:
      - grpc_network
    ports:
      - "8081:8081"
  
  black-list:
    image: black-list
    container_name: black-list
    networks:
      - grpc_network
    ports:
      - "8084:8082"
    environment:
      GRPC_SERVER_PORT: 9090
  
  grpc-nginx:
    image: nginx
    container_name: grpc-nginx
    networks:
      - grpc_network
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - black-list
      - user